import mongoose from 'mongoose'

const USER_SCHEMA = new mongoose.Schema({
    name:{
        type:String,
        default:""
    },
    lastname:{
        type:String,
        default:""
    },
    company:{
        type:String,
        default:""
    },
    password:{
        type:String
    },
    email:{
        type:String
    },
    country:{
        type:String
    },
    countryCode:{
        type:String
    },
    phones:{
        type:String,
    },
    Buildings: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'buildings'
        }
    ],
    updatedAt:{
        type:Date,
        default:`${new Date().toISOString()}`
    },
    notifications:[
        {
            Title:{
                type:String
            },
            summary:{
                type:String
            },
            to:{
                type:String
            }
        }
    ],
    scanned:[
        {
            buildingName:{
                type:String
            },
            scannedAt:{
                type:String
            },
            buildingID:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'buildings'
            }
        }
    ],
    verified:{
        type:Boolean,
        default:false
    },
    premium:{
        hasPremium:{
            type:Boolean,
            default:false
        },
        premiumType:{
            type:String,
            default:''
        },
        subscriptionId:{
            type:String,
            default:null
        },
        from:{
            type:Date,
        },
        to:{
            type:Date
        }
    },
    transactions:{
        type:Array
    },
    userType:{
        type:String,
        enum:['Individual','Company']
    },
    TwoFactorEnabled:{
        type:Boolean,
        default:false
    },
    trustedIPS:{
      type:[String],
      default:[]
    }
})

const USERS = mongoose.model('users',USER_SCHEMA);
export default USERS;
